 pipeline {
  agent any
 
  tools {
    nodejs "localNode"
  }
 
  stages {
    stage('Update'){
      steps{
        sh 'sh /Volumes/ssd256g/scripts/updateBolt.sh'
      }
    }
    stage('Build'){
      steps {
        sh 'sh /Volumes/ssd256g/scripts/startBolt.sh'
      }
    }
    stage('Test'){
      steps{
        sh ''' 
          cd /Volumes/ssd256g/bolt/BOLT-AUTOMATION
          npm i
          npm t
        '''
      }
    }
    stage('Delete'){
      steps{
        sh 'pm2 delete all'
      }
    }
  }
}