 pipeline {
  agent any
 
  tools {
    nodejs "localNode"
  }
 
  stages {
    stage('Update'){
      steps{
        sh ''' 
          sh /Volumes/ssd256g/scripts/updateBolt.sh
        '''
      }
    }
    stage('Build'){
      steps {
        sh '''
          cd /Volumes/ssd256g/gringotts
          pm2 start npm --name "gringotts" -- restart
          
          cd /Volumes/ssd256g/BOLT-TRUST
          pm2 start npm --name "trust" -- restart
          
          cd /Volumes/ssd256g/BOLT-KEYSTONE
          pm2 start npm --name "keystone" -- start
          
          cd /Volumes/ssd256g/BOLT-KEYCHAIN
          pm2 start npm --name "keychain" -- start

          cd /Volumes/ssd256g/BOLT-CURRENCY
          pm2 start npm --name "currency" -- restart

          cd /Volumes/ssd256g/HowinvestMockAPI
          pm2 start npm --name "HowinvestMockAPI" -- restart

          pm2 ls
          pm2 delete all
        '''
      }
    }
  }
}